name: bukateria
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  font_awesome_flutter: 10.1.0
  google_fonts: 2.2.0
  intl: 0.17.0
  page_transition: 2.0.4
  timeago: 3.1.0
  easy_debounce: 2.0.1
  json_path: 0.3.1
  flutter_awesome_select: ^6.4.0
  smooth_page_indicator: 1.0.0+2
  url_launcher: 6.0.15
  readmore: ^2.1.0
  pin_code_fields: ^7.4.0
  cupertino_icons: ^1.0.2
  get_cli: ^0.2.30
  weekday_selector: ^1.1.0
  flutter_advanced_switch: ^3.0.1
  shared_preferences: 2.0.11
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.9.2'
  flutter_native_splash: ^2.1.1

flutter_native_splash:
  color: '#fb4629'
  image: 'assets/images/splash.png'

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    # - assets/videos/
    # - assets/audios/
    # - assets/lottie_animations/
    # - assets/rive_animations/
    # - assets/pdfs/
